### ISSUE TITLE
Add google analytics tracking code

### ISSUE THREAD

**Issue by ksewalk** [healthmap/mriids2#148]
Add google analytics. We need to track page views and user demographics.

<script async src="https://www.googletagmanager.com/gtag/js?id=G-JCVJX06HL4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JCVJX06HL4');
</script>

**Comment by fernandodonaire** [comment]
Looks like this is how you add GA tracking to an app created using `create-react-app`: https://medium.com/brownbag/add-google-analytics-to-create-react-app-project-with-react-router-v4-f12b947262fc

**Comment by fernandodonaire** [comment]
It looks like `react-ga` doesn't support Google Analytics 4: https://github.com/react-ga/react-ga/issues/460

Asked Rachel, and she said that we can add a script like this one to the `index.html`: 

```
 <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=<tracking id>"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag('js', new Date());
                  gtag('config', '<tracking id>');
                  `,
          }}
        />
```
