### ISSUE TITLE
Issue with accessing routes directly

### ISSUE THREAD

**Issue by ksewalk** [healthmap/mriids2#173]
When refreshing the pages, such as /about url, the following occurs (https://dev-mriids.healthmap.org/about)
![Screen Shot 2021-03-31 at 10 49 47 AM](https://user-images.githubusercontent.com/20950416/113164219-e7bc3200-920e-11eb-9e0a-6a2ca2ce151a.png)

We also observe this with https://dev-mriids.healthmap.org/data and https://dev-mriids.healthmap.org/team

**Comment by skdandamudi** [comment]
Cloudfront expects a folder called /about  in the S3 bucket. Since it is not available you get an error message on refresh

**Comment by skdandamudi** [comment]
Updated Cloudfront  Paths.  Tested in dev and prod . works now
