### ISSUE TITLE
manifest errors showing up on dev site. We suspect it has to do with cloudfront as - we don't see this issue when using s3 url directly.

### ISSUE THREAD

**Issue by shaileshmahajan** [healthmap/mriids2#176]

**Comment by skdandamudi** [comment]
@shaileshmahajan @fernandodonaire  Looks like this is an issue only on dev site  that is occurring after we enabled Authentication. I disabled authentication on Dev https://dev-mriids.healthmap.org/ . Can  you please check

**Comment by shaileshmahajan** [comment]
@skdandamudi You are correct. It works without authentication

**Comment by skdandamudi** [comment]
This is a low priority as authentication is only for DEV. This is not a showstopper for prod release.

**Comment by ksewalk** [comment]
@skdandamudi can you confirm if this ticket is still in progress, or should we close as 'will not address'?

**Comment by skdandamudi** [comment]
@ksewalk Please close this for now. We will not address this at this point

**Comment by ksewalk** [comment]
@skdandamudi Thanks for confirming!
